name: Security

on:
  schedule:
    # Run security audit daily at 09:00 UTC
    - cron: '0 9 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-audit
        run: cargo install --locked cargo-audit

      - name: Run cargo-audit
        run: cargo audit

      - name: Install cargo-deny
        run: cargo install --locked cargo-deny

      - name: Run cargo-deny
        run: cargo deny check

  supply-chain:
    name: Supply Chain Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-vet
        run: cargo install --locked cargo-vet

      - name: Initialize cargo-vet if needed
        run: |
          if [[ ! -f supply-chain/config.toml ]]; then
            cargo vet init
          fi

      - name: Run cargo-vet
        run: cargo vet --locked